# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jgaehring.com
email: jamie@jgaehring.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Jamie Gaehring. I'm an independent web developer and consultant based in Brooklyn, New York. I've had over 10 years of experience working for GrowNYC's Greenmarket program, leading communications at Union Square. Today I'm providing farmers with access to better data tools and open source software to make their businesses and communities more sustainable in the 21st Century.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jgaehring.com" # the base hostname & protocol for your site
twitter_username: JamieGaehring
github_username:  jgaehring

# Build settings
markdown: kramdown

# Organization
sass:
  sass_dir: assets/css
